### ISSUE TITLE
PayPal Donate Button Goes to Patreon

### ISSUE THREAD

**Issue by crookedneighbor** [kraken-php/www#3]
Should probably update the icon to use a Patreon logo instead of using a PayPal icon.

**Comment by khelle** [comment]
There is no patreon icon in fontawesome which I have used. If you know of any other open source font that I could use instead, it would be welcomed. Right now I chose PayPal since even with Patreon it is the main payment method.

**Comment by khelle** [comment]
It has been changed in PR #4 .
